In [2]:
import pandas as pd

In [3]:
# 1. Create a Pandas Series from a Python list.

li = [10,20,30,40,50,60,70,80,90,100]

df = pd.Series(li , index=["A","B","C","D","E","F","G","H","I","J"])
df

A     10
B     20
C     30
D     40
E     50
F     60
G     70
H     80
I     90
J    100
dtype: int64

In [4]:
# 2. Create a DataFrame from a dictionary of lists 

dictionary = {
    "Name" : ["Satyajit Sahu"],
    "Age" : [20],
}
df = pd.DataFrame(dictionary)
df

            Name  Age
0  Satyajit Sahu   20

In [5]:
# 3. Read a CSV file into a Dataframe
df = pd.read_csv("customers-100.csv")
df.head(3)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/

In [6]:
# 4. Read a CSV file into a Dataframe
# first 5 rows
# last 5 rows
# random 5 rows

first = df.head(5)
last = df.tail(5)
random = df.sample(5)

print(first)
print(last) 
print(random)

   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter
1      2  1Ef7b82A4CAAD10    Preston    Lozano
2      3  6F94879bDAfE5a6        Roy     Berry
3      4  5Cef8BFA16c5e3c      Linda     Olsen
4      5  053d585Ab6b3159     Joanna    Bender

                           Company               City  \
0                  Rasmussen Group       East Leonard
1                      Vega-Gentry  East Jimmychester
2                    Murillo-Perry      Isabelborough
3  Dominguez, Mcmillan and Donovan                NaN
4         Martin, Lang and Andrade     West Priscilla

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718
1                    Djibouti              5153435776       686-620-1820x944
2         Antigua and Barbuda                   -1199    (496)978-3969x58947
3          Dominican Republic  001-808-617-6467x12895                  -9892
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486

                         Email Subscription Date                      Website
0     zunigavanessa@smith.info        24-08-2020   http://www.stephenson.com/
1              vmata@colon.com        23-04-2021        http://www.hobbs.com/
2          beckycarr@hogan.com        25-03-2020     http://www.lawrence.com/
3  stanleyblackwell@benson.org        02-06-2020   http://www.good-lyons.com/
4      colinalvarado@miles.net        17-04-2021  https://goodwin-ingram.com/
    Index      Customer Id First Name Last Name                Company  \
95     96  cb8E23e48d22Eae       Karl     Greer              Carey LLC
96     97  CeD220bdAaCfaDf       Lynn  Atkinson  Ware, Burns and Oneal
97     98  28CDbC0dFe4b1Db       Fred    Guerra          Schmitt-Jones
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer     Fitzgerald-Harrell
99    100  2354a0E336A91A1   Clarence    Haynes     Le, Nash and Cross

               City          Country               Phone 1  \
95     East Richard           Guyana   (188)169-1674x58692
96     New Bradview        Sri Lanka                 -3769
97       Ortegaland  Solomon Islands  +1-753-067-8419x7170
98  Lake Elijahview            Aruba         (530)311-9786
99        Judymouth         Honduras         (753)813-6941

                   Phone 2                           Email Subscription Date  \
95    001-841-293-3519x614                hhart@jensen.com        30-01-2022
96            605.413.3198               vkemp@ferrell.com        10-07-2021
97   +1-632-666-7507x92121                swagner@kane.org        18-09-2021
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        11-08-2021
99            783.639.1472          colleen91@faulkner.biz        11-03-2020

                              Website
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/
    Index      Customer Id First Name Last Name                      Company  \
88     89  efeb73245CDf1fF     Vernon      Kane            Carter-Strickland
31     32  679c6c83DD872d6        Tom  Trujillo                  Mcgee Group
94     95  BE91A0bdcA49Bbc    Darrell   Douglas  Newton, Petersen and Mathis
75     76  d40e89dCade7b2F      Debra    Riddle   Chang, Aguirre and Leblanc
93     94  54B5B5Fe9F1B6C5     Sherry     Young      Lee, Lucero and Johnson

                 City                       Country                Phone 1  \
88         Thomasfurt                         Yemen       114-854-1159x555
31  Cunninghamborough                       Denmark           416-338-3758
94       Daisyborough                          Mali  001-084-845-9524x1777
75         Colinhaven  United States Virgin Islands  +1-768-182-6014x14336
93       Frankchester               Solomon Islands           158-687-1764

              Phone 2                        Email Subscription Date  \
88       499-608-4612       hilljesse@barrett.info        15-04-2021
31      (775)890-7209         tapiagreg@beard.info        13-01-2022
94   001-769-564-6303     grayjean@lowery-good.com        17-02-2022
75      (303)961-4491      shieldskerry@robles.com        11-07-2020
93  (438)375-6207x003  alan79@gates-mclaughlin.com        04-04-2021

                          Website
88  http://www.duffy-hensley.net/
31  http://www.daniels-klein.com/
94             https://banks.biz/
75            http://kaiser.info/
93            https://travis.net/

In [7]:
# 5. Find:
# shape
# columns
# data types
# memory usage

shape = df.shape
print(shape)
column = df.columns
print(column)
data_type = df.dtypes
print(data_type)
memory = df.memory_usage
print(memory)

(100, 12)
Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')
Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object
<bound method DataFrame.memory_usage of     Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan                NaN
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda                   -1199
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka                   -3769
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        24-08-2020
1         686-620-1820x944                 vmata@colon.com        23-04-2021
2      (496)978-3969x58947             beckycarr@hogan.com        25-03-2020
3                    -9892     stanleyblackwell@benson.org        02-06-2020
4    001-199-446-3860x3486         colinalvarado@miles.net        17-04-2021
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        30-01-2022
96            605.413.3198               vkemp@ferrell.com        10-07-2021
97   +1-632-666-7507x92121                swagner@kane.org        18-09-2021
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        11-08-2021
99            783.639.1472          colleen91@faulkner.biz        11-03-2020

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]>

In [8]:
# 6. Select a single column using two different method
print(df.head())
df.query("Index == 2")  #method 1
df[df["Index"] == 2] #method 2

   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter
1      2  1Ef7b82A4CAAD10    Preston    Lozano
2      3  6F94879bDAfE5a6        Roy     Berry
3      4  5Cef8BFA16c5e3c      Linda     Olsen
4      5  053d585Ab6b3159     Joanna    Bender

                           Company               City  \
0                  Rasmussen Group       East Leonard
1                      Vega-Gentry  East Jimmychester
2                    Murillo-Perry      Isabelborough
3  Dominguez, Mcmillan and Donovan                NaN
4         Martin, Lang and Andrade     West Priscilla

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718
1                    Djibouti              5153435776       686-620-1820x944
2         Antigua and Barbuda                   -1199    (496)978-3969x58947
3          Dominican Republic  001-808-617-6467x12895                  -9892
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486

                         Email Subscription Date                      Website
0     zunigavanessa@smith.info        24-08-2020   http://www.stephenson.com/
1              vmata@colon.com        23-04-2021        http://www.hobbs.com/
2          beckycarr@hogan.com        25-03-2020     http://www.lawrence.com/
3  stanleyblackwell@benson.org        02-06-2020   http://www.good-lyons.com/
4      colinalvarado@miles.net        17-04-2021  https://goodwin-ingram.com/

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/

In [9]:
# 7. Select multiple columns
df[["Index","First Name","Company"]].head()

   Index First Name                          Company
0      1     Sheryl                  Rasmussen Group
1      2    Preston                      Vega-Gentry
2      3        Roy                    Murillo-Perry
3      4      Linda  Dominguez, Mcmillan and Donovan
4      5     Joanna         Martin, Lang and Andrade

In [10]:
# 8. Select rows using
# .loc
# .iloc

df.head()
df.iloc[2,4]
df.loc[1,"Company"] # uses labels

'Vega-Gentry'

In [11]:
# 9.Filter rows where:
# a column value is greater than a given number
# multiple conditions are true

# df.query("Index > 80")
df.query("Index > 80 and Index < 90")

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
80,81,D6CEAfb3BDbaa1A,Leslie,Jennings,Blankenship-Arias,Coreybury,Micronesia,629.198.6346,075.256.0829,corey75@wiggins.com,13-11-2021,https://www.juarez.com/
81,82,Ebdb6F6F7c90b69,Kathleen,Mckay,"Coffey, Lamb and Johnson",Lake Janiceton,Saint Vincent and the Grenadines,(733)910-9968,(691)247-4128x0665,chloelester@higgins-wilkinson.com,12-09-2021,http://www.owens-mooney.com/
82,83,E8E7e8Cfe516ef0,Hunter,Moreno,Fitzpatrick-Lawrence,East Clinton,Isle of Man,(733)833-6754,001-761-013-7121,isaac26@benton-finley.com,28-12-2020,http://walls.info/
83,84,78C06E9b6B3DF20,Chad,Davidson,Garcia-Jimenez,South Joshuashire,Oman,8275702958,(804)842-4715,justinwalters@jimenez.com,15-11-2021,http://www.garner-oliver.com/
84,85,03A1E62ADdeb31c,Corey,Holt,"Mcdonald, Bird and Ramirez",New Glenda,Fiji,001-439-242-4986x7918,3162708934,maurice46@morgan.com,18-02-2020,http://www.watson.com/
85,86,C6763c99d0bd16D,Emma,Cunningham,Stephens Inc,North Jillianview,New Zealand,128-059-0206x60217,(312)164-4545x2284,walter83@juarez.org,13-05-2022,http://www.reid.info/
86,87,ebe77E5Bf9476CE,Duane,Woods,Montoya-Miller,Lyonsberg,Maldives,(636)544-7783x7288,(203)287-1003x5932,kmercer@wagner.com,21-07-2020,http://murray.org/
87,88,E4Bbcd8AD81fC5f,Alison,Vargas,"Vaughn, Watts and Leach",East Cristinabury,Benin,365-273-8144,053-308-7653x6287,vcantu@norton.com,10-11-2020,http://mason.info/
88,89,efeb73245CDf1fF,Vernon,Kane,Carter-Strickland,Thomasfurt,Yemen,114-854-1159x555,499-608-4612,hilljesse@barrett.info,15-04-2021,http://www.duffy-hensley.net/

In [12]:
#10 Reset index and set a new index
df_reset = df.reset_index(drop=True)
df_reset

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",NaN,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [13]:
#11. Detect  missing values
df.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            3
Company              8
City                 9
Country              2
Phone 1              4
Phone 2              1
Email                3
Subscription Date    0
Website              0
dtype: int64

In [14]:
#12. Replace missing values with:
#mean
#median
#mode
import pandas as pd
new_df = pd.read_excel("data.xlsx")
new_df
new_df.fillna(new_df.mean(numeric_only=True), inplace=True)
new_df.fillna(new_df.mode(numeric_only=True), inplace=True)

In [15]:
# #13. Drop rows and columns with missing values

# new_df = new_df.dropna(axis=1) #column
# new_df = new_df.dropna(axis=1) #Rows
# new_df

In [16]:
#14. Rename columns
new_df = new_df.rename(columns={"Name" : "_name"})

In [17]:
new_df

    _name  Science   Math  English  Physics  Chemistry
0   Satya      100  100.0    100.0     75.5  74.428571
1    Bixi       23   23.0     74.4     75.5  75.000000
2    Mixi       42   63.0     74.4     75.5  69.000000
3    Cici       36   61.4     78.0     75.5  75.000000
4    Sexi       69   61.4     36.0     89.0  74.428571
5    Mexi       86   36.0     74.4     75.5  75.000000
6    Texi       96   85.0     74.4     55.0  35.000000
7  Cheski       48   61.4     79.0     79.0  96.000000
8  Cheski       48   61.4     79.0     79.0  96.000000

In [18]:
# 15. Change data type of a column
new_df["Science"] = new_df["Science"].astype('float64')

In [19]:
new_df

    _name  Science   Math  English  Physics  Chemistry
0   Satya    100.0  100.0    100.0     75.5  74.428571
1    Bixi     23.0   23.0     74.4     75.5  75.000000
2    Mixi     42.0   63.0     74.4     75.5  69.000000
3    Cici     36.0   61.4     78.0     75.5  75.000000
4    Sexi     69.0   61.4     36.0     89.0  74.428571
5    Mexi     86.0   36.0     74.4     75.5  75.000000
6    Texi     96.0   85.0     74.4     55.0  35.000000
7  Cheski     48.0   61.4     79.0     79.0  96.000000
8  Cheski     48.0   61.4     79.0     79.0  96.000000

In [20]:
#16. Remove duplicate rows.
new_df = new_df.drop_duplicates()

In [21]:
new_df

    _name  Science   Math  English  Physics  Chemistry
0   Satya    100.0  100.0    100.0     75.5  74.428571
1    Bixi     23.0   23.0     74.4     75.5  75.000000
2    Mixi     42.0   63.0     74.4     75.5  69.000000
3    Cici     36.0   61.4     78.0     75.5  75.000000
4    Sexi     69.0   61.4     36.0     89.0  74.428571
5    Mexi     86.0   36.0     74.4     75.5  75.000000
6    Texi     96.0   85.0     74.4     55.0  35.000000
7  Cheski     48.0   61.4     79.0     79.0  96.000000

In [22]:
#17. Aggregation & GroupBy 
# Find:
#mean 
#sum
#count
#max
#min

df2 = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],                                                                                                        
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [18, 30, 20, 60, 35, 55,46, 38],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [23]:
df2.groupby("Department")["Salary"].mean()
df2.groupby("Team")["Age"].max()

Team
A    30
B    60
C    55
D    46
Name: Age, dtype: int64

In [24]:
df2.groupby("Department")["Salary"].agg(
    avg_salary = "max",
    Age = "max",
    date = "count"
)

            avg_salary  Age  date
Department
HR                  90   90     2
IT                  85   85     2
Marketing           92   92     2
Sales               80   80     2

In [25]:
# 18. Group data by a categorical column and calculate:
# 1. average
# 2. total

df2.groupby("Department")["Salary"].mean()
df2.groupby("Department")["Salary"].sum()

Department
HR           175
IT           163
Marketing    180
Sales        155
Name: Salary, dtype: int64

In [26]:
# 19. Sort values by:
# 1. one column
# 2. multiple columns

df2.sort_values("Salary",ascending=False)
df2.sort_values(["Salary","Age"],ascending=False)

  Department Team Gender  Salary  Age   JoinDate
4  Marketing    C      M      92   35 2020-05-30
1         HR    A      F      90   30 2020-02-15
5  Marketing    C      F      88   55 2020-06-25
3         IT    B      F      85   60 2021-04-10
0         HR    A      M      85   18 2020-01-10
7      Sales    D      F      80   38 2021-08-01
2         IT    B      M      78   20 2021-03-20
6      Sales    D      M      75   46 2021-07-15

In [27]:
# 20. Create a new column based on a condition.
df2 = df2.drop_duplicates()
import numpy as np

mean_salary = df2["Salary"].mean()
max_salary = df2["Salary"].max()

df2["Mean Salary"] = np.where(
    df2["Gender"] == "M",    #if not not use pandas
    mean_salary,
    max_salary
)

df2

  Department Team Gender  Salary  Age   JoinDate  Mean Salary
0         HR    A      M      85   18 2020-01-10       84.125
1         HR    A      F      90   30 2020-02-15       92.000
2         IT    B      M      78   20 2021-03-20       84.125
3         IT    B      F      85   60 2021-04-10       92.000
4  Marketing    C      M      92   35 2020-05-30       84.125
5  Marketing    C      F      88   55 2020-06-25       92.000
6      Sales    D      M      75   46 2021-07-15       84.125
7      Sales    D      F      80   38 2021-08-01       92.000

In [28]:
# 21. Use .apply() with a custom function. 
df2["Young_Old"] = df2['Age'].apply(lambda x : "Young" if x <= 25 else "Old")
df2

  Department Team Gender  Salary  Age   JoinDate  Mean Salary Young_Old
0         HR    A      M      85   18 2020-01-10       84.125     Young
1         HR    A      F      90   30 2020-02-15       92.000       Old
2         IT    B      M      78   20 2021-03-20       84.125     Young
3         IT    B      F      85   60 2021-04-10       92.000       Old
4  Marketing    C      M      92   35 2020-05-30       84.125       Old
5  Marketing    C      F      88   55 2020-06-25       92.000       Old
6      Sales    D      M      75   46 2021-07-15       84.125       Old
7      Sales    D      F      80   38 2021-08-01       92.000       Old

In [29]:
# 21. Use .map() with a custom function. 
gender = {"M" : "Male","F":"Female"}
df2["Gender"]=df2["Gender"].map(gender)

In [30]:
df2

  Department Team  Gender  Salary  Age   JoinDate  Mean Salary Young_Old
0         HR    A    Male      85   18 2020-01-10       84.125     Young
1         HR    A  Female      90   30 2020-02-15       92.000       Old
2         IT    B    Male      78   20 2021-03-20       84.125     Young
3         IT    B  Female      85   60 2021-04-10       92.000       Old
4  Marketing    C    Male      92   35 2020-05-30       84.125       Old
5  Marketing    C  Female      88   55 2020-06-25       92.000       Old
6      Sales    D    Male      75   46 2021-07-15       84.125       Old
7      Sales    D  Female      80   38 2021-08-01       92.000       Old

In [31]:
#24. Bin numerical data using pd.cut().
df2["Age_Group"]  = pd.cut(df2["Age"],bins=[0,20,40,60],labels=["0-20", "20-40", "40-60"])
df2

,Department,Team,Gender,Salary,Age,JoinDate,Mean Salary,Young_Old,Age_Group
0,HR,A,Male,85,18,2020-01-10,84.125,Young,0-20
1,HR,A,Female,90,30,2020-02-15,92.000,Old,20-40
2,IT,B,Male,78,20,2021-03-20,84.125,Young,0-20
3,IT,B,Female,85,60,2021-04-10,92.000,Old,40-60
4,Marketing,C,Male,92,35,2020-05-30,84.125,Old,20-40
5,Marketing,C,Female,88,55,2020-06-25,92.000,Old,40-60
6,Sales,D,Male,75,46,2021-07-15,84.125,Old,40-60
7,Sales,D,Female,80,38,2021-08-01,92.000,Old,20-40

In [32]:
#25. Merge two DataFrames:

# inner join
# left join
# right join

import pandas as pd
# DataFrame 1
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Ram', 'Shyam', 'Mohan', 'Sita']
})

# DataFrame 2
df2 = pd.DataFrame({
    'ID': [3, 4, 5, 6],
    'Marks': [78, 88, 90, 95]
})

inner_join = pd.merge(df1,df2, on='ID',how="inner")
left_join = pd.merge(df1,df2, on='ID',how="left")   ## isse hum koi bhi particular column ko target kar ke concate kr skte h 
right_join = pd.merge(df1,df2, on='ID',how="right")


print(inner_join)
print("-------------------------------------")
print(left_join)
print("-------------------------------------")
print(right_join)

   ID   Name  Marks
0   3  Mohan     78
1   4   Sita     88
-------------------------------------
   ID   Name  Marks
0   1    Ram    NaN
1   2  Shyam    NaN
2   3  Mohan   78.0
3   4   Sita   88.0
-------------------------------------
   ID   Name  Marks
0   3  Mohan     78
1   4   Sita     88
2   5    NaN     90
3   6    NaN     95

In [33]:
# 26. Concatenate DataFrames:
# row-wise
# column-wise

row_ = pd.concat([df1,df2],axis=0)
column =  pd.concat([df1,df2],axis=1)   ## isme direct concat ho jayega without targeting any column
print(row_)
print(column)

   ID   Name  Marks
0   1    Ram    NaN
1   2  Shyam    NaN
2   3  Mohan    NaN
3   4   Sita    NaN
0   3    NaN   78.0
1   4    NaN   88.0
2   5    NaN   90.0
3   6    NaN   95.0
   ID   Name  ID  Marks
0   1    Ram   3     78
1   2  Shyam   4     88
2   3  Mohan   5     90
3   4   Sita   6     95

In [34]:
#27. Pivot and melt a DataFrame.
df3 = pd.DataFrame({
    "Name" : ["Satyajit sahu","Ayushi Kumari"],
    "Score" : [10,20],
    "Subject" : ["Science","Commerece"]
})
print(df3)
pivot = df3.pivot_table(index="Name", columns="Subject", values="Score", aggfunc="mean")
print(pivot)
melt = pivot.reset_index().melt(id_vars="Name", var_name="Subject", value_name="Score")
print(melt)

            Name  Score    Subject
0  Satyajit sahu     10    Science
1  Ayushi Kumari     20  Commerece
Subject        Commerece  Science
Name
Ayushi Kumari       20.0      NaN
Satyajit sahu        NaN     10.0
            Name    Subject  Score
0  Ayushi Kumari  Commerece   20.0
1  Satyajit sahu  Commerece    NaN
2  Ayushi Kumari    Science    NaN
3  Satyajit sahu    Science   10.0

In [35]:
#28. Given student marks:
# find topper
# find average
# count students above average
import pandas as pd
df = pd.read_csv("da.csv")
print(df)

      Name    Subject  Marks
0      Ram       Math     85
1    Shyam    Physics     80
2    Mohan  Chemistry     92
3     Sita    Biology     88
4    Geeta    English     82
5     Amit       Math     95
6     Neha    Physics     84
7    Rohit  Chemistry     78
8     Tina    Biology     91
9   Vikram    English     79
10   Kiran       Math     87
11    Ravi    Physics     90
12   Anita  Chemistry     85
13   Priya    Biology     92
14   Sunil    English     80
15   Deepa       Math     89
16    Ajay    Physics     86
17   Pooja  Chemistry     88
18   Kajal    Biology     91
19   Vikas    English     83

In [36]:
count = df["Name"].count()
marks = df["Marks"].sum()
average = marks / count
print(average)

86.25

In [37]:
above_avg = 0
for i in range(len(df)):
    if df["Marks"][i] > average :
        above_avg+=1
print(above_avg)

10

In [38]:
max_= 0 
for i in range(len(df)) :
    if max_ < df["Marks"][i] :
        max_ = df["Marks"][i]
        result = df.loc[i,["Name","Marks", "Subject"]]
print(result)

Name       Amit
Marks        95
Subject    Math
Name: 5, dtype: object

In [39]:
#29. Gives sales data:
# monthly total sales
#best selling product

import pandas as pd 
df = pd.read_csv("product.csv")
print(df)

   Month   Product  Sales
0    Jan  ProductA    120
1    Jan  ProductB    150
2    Jan  ProductC     90
3    Feb  ProductA    130
4    Feb  ProductB    170
5    Feb  ProductC    110
6    Mar  ProductA    140
7    Mar  ProductB    160
8    Mar  ProductC    100
9    Apr  ProductA    150
10   Apr  ProductB    180
11   Apr  ProductC    120
12   May  ProductA    160
13   May  ProductB    190
14   May  ProductC    130
15   Jun  ProductA    170
16   Jun  ProductB    200
17   Jun  ProductC    140
18   Apr  ProductA    145
19   Jan  ProductA    180
20   Jan  ProductB    120
21   Jan  ProductC    160
22   Feb  ProductA    190
23   Feb  ProductB    130
24   Feb  ProductC    170
25   Mar  ProductA    125

In [40]:
total_monthly = df.groupby("Month",as_index=False)[["Sales","Product"]].sum()
print(total_monthly)

  Month  Sales                                           Product
0   Apr    595                  ProductAProductBProductCProductA
1   Feb    900  ProductAProductBProductCProductAProductBProductC
2   Jan    820  ProductAProductBProductCProductAProductBProductC
3   Jun    510                          ProductAProductBProductC
4   Mar    525                  ProductAProductBProductCProductA
5   May    480                          ProductAProductBProductC

In [41]:
best_selling = df.groupby("Product")["Sales"].sum()
print(best_selling)

Product
ProductA    1510
ProductB    1300
ProductC    1020
Name: Sales, dtype: int64

In [42]:
# 30. Given timestamp data:
# extract year, month, day
# filter by date range

df = pd.read_csv('timestamp_sales.csv')
df[['Date','Time']] = df['Timestamp'].str.split(' ',expand=True)
df = df.drop(columns=["Timestamp"])
df

   Sales   Product        Date      Time
0    120  ProductA  2025-01-05  10:30:00
1    150  ProductB  2025-01-15  14:20:00
2    100  ProductC  2025-02-02  09:15:00
3    200  ProductA  2025-02-18  16:45:00
4    180  ProductB  2025-03-03  11:10:00
5    220  ProductC  2025-03-22  13:30:00
6    210  ProductA  2025-04-10  12:00:00
7    190  ProductB  2025-04-28  15:50:00
8    250  ProductC  2025-05-05  10:05:00
9    300  ProductA  2025-05-18  17:20:00